### ISSUE TITLE
DARK MODE IN CFF EXPLORER

### ISSUE THREAD

**Issue by x00tox01** [vic4key/CFF_VExtension#2]
CAN WE ADD DARK MODE FEATURE IN CFF?

**Comment by vic4key** [comment]
It's possible but unfortunately I have no time to do do it at this time.
The dark mode can enable by the repo [win32-dark-mode]( https://github.com/ysc3839/win32-darkmode) (used by notepad++, process hacker, etc).
If you have time and codable with C++, let give a try. 😛
